# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_name:                    "Homer J. Simpson"
resume_title:                   "Nuclear Safety Inspector"
resume_contact_email:           "homerjsimpson@youremailaddress.com"
