# Site settings
title: "Jeff Anderson's Work-In-Progress Resume"
description: "Jeff Anderson's Work-In-Progress Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jeff Anderson"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jeff@jeffanderson.dev"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>This resume is an MVP.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jander99"
  resume_twitter_url:           "http://twitter.com/jander99"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jander99"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://jeffanderson.dev"
  resume_medium_url:            "https://medium.com/@jander99"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
