# Site settings
title: "Liliana Spadaro"
description: "Curriculum vitæ Liliana Spadaro."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Liliana Spadaro"
resume_title:                   "Storica dell'arte, Curatrice"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "info@lilianaspadaro.it"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "info@lilianaspadaro.it"
display_header_contact_info:    "false"

resume_header_intro: "<p>Storica dell'Arte e curatrice, i miei studi rispecchiano le mie passioni, l'arte contemporanea e le ultime tendenze. Mi piace essere a contatto con le realtà più dinamiche del periodo, scambiare idee e influenze con chi ha fatto della creatività il suo mestiere. Amo il mio gatto, viaggiare e la musica rock. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/orbitarte"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/AssociazioneOrbitArte/"
  resume_linkedin_url:          "https://www.linkedin.com/in/liliana-spadaro-15732616a"
  resume_instagram_url:         "https://www.instagram.com/associazioneorbitarte/"
  resume_website_url:           "https://www.lilianaspadaro.it"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
