# Site settings
title: 'Nikhil Peri | Resume'

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  true
resume_name:                    'Nikhil Peri'
resume_title:                   'Electrical Engineer & Computer Scientist'
resume_contact_email:           'nperi104@uottawa.ca'
resume_contact_telephone:       '613-265-9279'
resume_contact_address:         '48 Bridesburg Drive, Toronto Ontario'
resume_header_intro: >
  I am a passionate maker and aim to be a swiss army knife of skills.
  I do not claim to know everything; but do claim to be able to learn anything.
  I am a licensed pilot, founder of uOttawa Rocketry and have been a garage tinker'er my entire life.
  I live with the philosophy <i>- Do what you can't</i>, and wish to work in an environment where
  people get the license to step out of their comfort zone. This resume is a short story of the work
  I have done, if you would like to hear more I would be happy to chat

# use 'yes' to display the email contact button,
# 'no' to display an 'I'm not looking for work' message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        'yes'

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_projects:        true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            'https://github.com/nikhilperi'
  # resume_facebook_url:          'insert Facebook URL here'
  resume_linkedin_url:          'https://www.linkedin.com/in/nikhil-peri-511639109'
  # resume_instagram_url:         'insert your Instagram URL here'
  resume_website_url:           'http://nikhilperi.github.io'
resume_print_social_links:      true

# Design settings
resume_theme:                   default
