# Site settings
title: "Adam Sealey Resume"
description: "A resume for Adam Sealey"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Adam Sealey"
#resume_title:                   "Senior Director, Office of Cybersecurity & Chief of Staff"
resume_title:                   "Senior Director, Cybersecurity Strategy & Chief of Staff"
#resume_title:                   "Cybersecurity Executive with emphasis on strategic development, organizational transformation, and data-driven execution."
resume_contact_email:           "adam.sealey@gmail.com"
resume_contact_telephone:       "925-709-4565"
resume_contact_address:         "Portland, Oregon"
resume_header_contact_info: "925-709-4565 | adam.sealey@gmail.com"
resume_header_intro: "<p>Strategic, data-driven Cybersecurity Executive with 15+ years' experience
across multiple industries, including Retail (Nike), Higher Education, and Government.  A results-oriented leader with
a proven track record of results in risk-driven strategic development, organizational transformation,
data-driven executive reporting, and talent management.</p>"


# Intro Snips
#building highly effective, data driven security programs and leading transformational change.</p>"
#resume_header_intro: "<p>Strategic, data-driven Cybersecurity Executive with 15+ years' experience in
#risk-driven strategic development, organizational transformation,  data-driven executive reporting, and
#talent management.</p>"

# Old (Pre-2020)
#resume_header_intro: "<p>Experienced Information Security and Analytics leader with a demonstrated history of working in retail, government,
#and higher education. Strong blend of technical capability with a passion for inspiring teams.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/asealey"
  resume_twitter_url:           "https://twitter.com/adamsealey"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/adamsealey/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.adamsealey.com/resume"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
