# Site settings
title: "Alvin Piter | Resume"
description: "Alvin Piter | Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alvin Piter"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "alpiter10@gmail.com"

resume_header_contact_info:     "alpiter10@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

resume_header_intro: "<p>I am a software engineer previously work for Bukalapak as backend engineer. My interests are including, but not limited to, software engineering, developing algorithm and data structures, and teaching. I am currently seeking an employment as frontend engineer, preferably from a company which use React framework. </p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
resume_section_achievements:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alvinpiter"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
