# Site settings
title: "Florestan Lefevre"
description: "Florestan Lefevre"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Florestan Lefevre"
resume_title:                   "Aspiring Product Manager"
resume_contact_email:           "FlorestanLefevre@gmail.com"
resume_contact_telephone:       "619 496 4428"
resume_contact_address:         "San Diego, CA"
resume_header_contact_info: "San Diego, CA | 619 496 4428 | FlorestanLefevre@gmail.com"
resume_header_intro: "<p>I am a creative engineer, with a startup mindset, who learned how to code @LeWagon. I am an agile learner and I want to develop my skills in all sorts of challenging situations."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/floustao"
  resume_twitter_url:           "http://twitter.com/floustao"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/florestanlefevre"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://seeedr.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
