# Site settings
title: "个人简历"
description: "一个个人简历网址."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "苏盼盼"
resume_title:                   "VP of Global Communications"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "supanpan199919@163.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+86 188 8806 0737"
resume_contact_address:         "NanJing,JiangSu"

resume_header_contact_info:     "NanJing,JiangSu • +86 188 8806 0737 • supanpan199919@163.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>性别男，爱好女</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/AtwoodPa"
  resume_gitee_url:           "https://gitee.com/su-panpan0419"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
