# Site settings
title: "Lidan Yang's Resume"
description: "Lidan Yang's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Lidan Yang"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nellyyanglidan@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "213-255-1662"
resume_contact_address:         "Los Angeles"

resume_header_contact_info:     "Los Angeles • 213-255-1662 • nellyyanglidan@yahoo.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Actively seeking for full-time job. A current master candidate in Computer Science at University of Southern California, set to graduate at May 2019. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/lidan-yang-2b5958132/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
