# Site settings
title: "Mattia Tupone resume"
description: "mattups - resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mattia Tupone"
resume_title:                   "SysAdmin/IT Technician"
resume_contact_email:
  "tupone.mattia@gmail.com"
resume_header_contact_info: "Lanciano (CH), Italy | tupone.mattia@gmail.com"
resume_header_intro: "<p>I'm a 22 years SysAdmin/DevOps based in Italy with the passion for IT systems and coding. Moving across servers, code and deployments, i started working as a professional in 2016 gaining and maturing experience day-by-day, always looking for new technologies and methods.
Skilled with virtualization technologies as VMware vSphere Suite and Microsoft Windows/Linux ecosystems.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mattups"
  #resume_twitter_url:           "https://twitter.com/mattia_tupone"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mattia-tupone-660450a6/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://mattups.github.io/resume/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
